version: '3.1'

services:
  express-starter-kit:
    image: express-starter-kit
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - mongo  
  mongo:
    image: mongo
    ports: 
      - 27017:27017
