version: '3.1'

services:
  express-starter-kit:
    image: express-starter-kit
    build: .
    ports:
      - 3000:3000
    links:
      - mongo  
  mongo:
    image: mongo:4.2
    ports: 
      - 27017:27017

